apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argocd-test
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
